version: '3.3'

services:
  app:
    image: imleafz/mattermost:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "5"
          memory: "512m"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    volumes:
      - ./data/mattermost/config.json:/usr/local/mattermost/config/config.json
      - ./data/mattermost:/data/mattermost
    networks:
      - net
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.port=80"
      - "traefik.backend=mattermost"
      - "traefik.frontend.rule=Host: xxx"

  db:
    image: mysql:latest
    deploy:
      mode: global
      resources:
        limits:
          cpus: "10"
          memory: "1024m"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD
