version: '3.3'

services:
  app:
    image: imleafz/vlmcsd:latest
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.01"
          memory: "32M"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 15s
    ports:
      - "1688:1688"
    networks:
      - net

networks:
  net:
